### PR TITLE
add prepare script to prevent missing dist files

### PR DESCRIPTION
**Pull request by vankop**
Since 1.0.4 version this package does not working correctly. `main` field in package.json could not be resolved

### CODE REVIEW

**Comment by theothersideofgod** [comment]
@danwang @fregante hey, guys could you merge this?

we need you guys help. thanks so much.

@fregante why? did i miss anything?

**Comment by voskresla** [comment]
@fregante can u explain emoji? )

**Comment by fregante** [comment]
Don't ping me, it's not my repo. Plus it had only been 10 hours since the PR was open, that's way too early to ping anyone.

**Comment by danwang** [comment]
Should be fixed in version 1.1.0: https://www.npmjs.com/package/yaml-jest

**Pull request closed without merging**
